services:
    setmatch-db:
        image: 'postgres'
        ports:
            - "5432:5432"
        env_file: .env
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        restart: always
        volumes:
            - ./data:/var/lib/postgresql/data
